#!/bin/bash

echo "🚀 Khởi động OCOP Đồng Nai E-commerce App"
echo "========================================"

echo ""
echo "📱 Frontend Setup:"
echo "1. Chuyển đến thư mục frontend:"
echo "   cd ocop_frontend"
echo ""
echo "2. Cài đặt dependencies:"
echo "   npm install"
echo ""
echo "3. Chạy ứng dụng:"
echo "   npm start"
echo ""
echo "   Hoặc chạy trên thiết bị cụ thể:"
echo "   npm run android    # Android"
echo "   npm run ios        # iOS"
echo "   npm run web        # Web"
echo ""

echo "🖥️ Backend Setup:"
echo "1. Chuyển đến thư mục backend:"
echo "   cd ocop_backend"
echo ""
echo "2. Cài đặt dependencies:"
echo "   npm install"
echo ""
echo "3. Chạy server:"
echo "   npm start"
echo ""
echo "   Server sẽ chạy tại: http://localhost:5000"
echo ""

echo "📊 Dữ liệu có sẵn:"
echo "✅ 10 sản phẩm đặc sản Đồng Nai"
echo "✅ 4 danh mục sản phẩm"
echo "✅ Hình ảnh sản phẩm từ assets"
echo "✅ Mock data fallback khi API không khả dụng"
echo ""
echo "🎯 Tính năng chính:"
echo "✅ Hiển thị sản phẩm với hình ảnh"
echo "✅ Giỏ hàng và đặt hàng"
echo "✅ Authentication (JWT)"
echo "✅ Tìm kiếm và lọc sản phẩm"
echo "✅ Responsive UI"
echo ""

echo "🔗 API Endpoints:"
echo "GET  /api/products     - Danh sách sản phẩm"
echo "GET  /api/categories   - Danh mục sản phẩm"
echo "POST /api/auth/login   - Đăng nhập"
echo "GET  /api/cart         - Giỏ hàng"
echo ""

echo "🎨 UI Features:"
echo "✅ Home screen với banners"
echo "✅ Product cards với hình ảnh"
echo "✅ Category navigation"
echo "✅ Search functionality"
echo "✅ Cart management"
echo ""

echo "📱 Mobile Optimized:"
echo "✅ Touch gestures"
echo "✅ Responsive layout"
echo "✅ Native performance"
echo "✅ Offline fallback"
echo ""

echo "🎉 Sẵn sàng để chạy!"
echo "Bắt đầu với: npm start trong từng thư mục"
echo ""
echo "Happy coding! 🚀✨"
